version: "3"  

tasks:  
  default:
    cmds:  
      - task: generate  
  generate: 
    aliases:
      - gen  
    desc: "Generate go-proto files"  
    cmds:  ## Тут описываем необходимые bash-команды
      - protoc -I ../proto -I googleapis ../proto/sso/*.proto --go_out=../gen/go/ --go_opt=paths=source_relative --go-grpc_out=../gen/go/ --go-grpc_opt=paths=source_relative --grpc-gateway_out=../gen/go/ --grpc-gateway_opt=paths=source_relative --openapiv2_out=../gen/go/ --openapiv2_opt=allow_merge=true,merge_file_name=api